#!/bin/sh
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/abagheri.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/acweaver.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/AlexDWong.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/almell.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/arlynr.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/arshajii.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/auwong.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/awlu450.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/baggio-.git
git clone https://dachopra:ASHAmini9833$github.com/Giles-ECE-BU/barrasso.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/brandonphan.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/brewtonb.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/caitiem.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/CarrieCramer.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/cbeng973.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/ChristineDuong.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/cjduffett.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/codies27.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/CristianM15.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/danielv775.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/danielv775.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/deemak.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/dereckf.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/dkim212.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/drummingjack2.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/etcarson.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/fordy13.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/fsavoca.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/hongjooy.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/jbelang.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/jeffzhu7.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/jeremybensabat.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/jonckim.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/kbenja.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/ksingh93.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/ksparakis.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/luk2015.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/minggLu.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/mleeza.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/nmemme.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/nmorrisn.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/nrjbs87.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/peteg944.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/pf8363.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/pmoy.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/pzhang94.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/rscharf.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/SamC125.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/sbobhate.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/snoops149.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/Sweettomato.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/taranac.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/tierneyj.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/tjoncas.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/winstonchen.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/YElyousfi.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/zganger.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/Zoishipster.git
git clone https://dachopra:ASHAmini9833$@github.com/Giles-ECE-BU/zsarkis.git
